<?php
session_start();
if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit;
}

require_once 'config/database.php';
$database = new Database();
$conn = $database->getConnection();

$query = "SELECT balance FROM users WHERE id = :user_id";
$stmt = $conn->prepare($query);
$stmt->bindParam(':user_id', $_SESSION['user_id']);
$stmt->execute();
$user = $stmt->fetch(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html>
<html>
<head>
    <title>Chicken Run - Casino</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/chicken.css">
</head>
<body>
    <div class="game-container">
        <header>
            <h1>🐔 Chicken Run</h1>
            <div class="user-info">
                <span>Welcome, <?php echo htmlspecialchars($_SESSION['username']); ?></span>
                <span class="balance">Balance: $<span id="userBalance"><?php echo number_format($user['balance'], 2); ?></span></span>
                <a href="game.php" class="btn btn-small">Aviator Game</a>
                <button onclick="showWallet()" class="btn btn-small">Wallet</button>
                <a href="logout.php" class="btn btn-small">Logout</a>
            </div>
        </header>

        <div class="chicken-game-area">
            <div class="game-info">
                <div class="info-card">
                    <h3>Current Bet</h3>
                    <p id="currentBet">$0.00</p>
                </div>
                <div class="info-card">
                    <h3>Multiplier</h3>
                    <p id="currentMultiplier">1.00x</p>
                </div>
                <div class="info-card">
                    <h3>Potential Win</h3>
                    <p id="potentialWin">$0.00</p>
                </div>
                <div class="info-card">
                    <h3>Bones Collected</h3>
                    <p id="bonesCollected">0</p>
                </div>
            </div>

            <div class="chicken-grid" id="chickenGrid">
                <!-- Grid will be generated by JavaScript -->
            </div>

            <div class="game-controls">
                <div class="bet-section">
                    <label>Bet Amount:</label>
                    <input type="number" id="betAmount" min="1" value="10" step="1">
                    <button onclick="startChickenGame()" id="startButton" class="btn btn-primary">Start Game ($10)</button>
                    <button onclick="cashOutChicken()" id="cashoutButton" class="btn btn-success" disabled>Cash Out</button>
                </div>
                <div class="difficulty-section">
                    <label>Difficulty:</label>
                    <select id="difficulty">
                        <option value="easy">Easy (8 bones, 2 bombs)</option>
                        <option value="medium" selected>Medium (6 bones, 4 bombs)</option>
                        <option value="hard">Hard (4 bones, 6 bombs)</option>
                    </select>
                </div>
            </div>

            <div class="game-instructions">
                <h3>How to Play:</h3>
                <ul>
                    <li>🐔 Choose your bet amount and difficulty level</li>
                    <li>🦴 Click tiles to reveal bones (good) or bombs (game over)</li>
                    <li>💰 Each bone increases your multiplier</li>
                    <li>✅ Cash out anytime to secure your winnings</li>
                    <li>💣 Hit a bomb and lose everything!</li>
                </ul>
            </div>
        </div>

        <div class="chicken-history">
            <h3>Recent Games</h3>
            <div id="chickenHistory"></div>
        </div>
    </div>

    <!-- Wallet Modal (same as aviator) -->
    <div id="walletModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeWallet()">&times;</span>
            <h2>Wallet</h2>
            <div class="wallet-actions">
                <div>
                    <h3>Deposit</h3>
                    <input type="number" id="depositAmount" min="1" placeholder="Amount">
                    <button onclick="deposit()" class="btn btn-primary">Deposit</button>
                </div>
                <div>
                    <h3>Withdraw</h3>
                    <input type="number" id="withdrawAmount" min="1" placeholder="Amount">
                    <button onclick="withdraw()" class="btn">Withdraw</button>
                </div>
            </div>
        </div>
    </div>

    <script src="assets/js/chicken.js"></script>
</body>
</html>